### ISSUE TITLE
SF package for R

### ISSUE THREAD

**Issue by ghost** [Jtsmith275/RStudioShiny-nginx#4]
I don't know why, but `sf` and `rgdal` were not installed with this script.  Looking at the documentation they need `libgeos-dev` (line 42), `libproj-dev` (line 51), and `libudunits2-dev` (line 55), which should be installed at those lines.  I reinstalled:
`sudo apt update -y && sudo apt install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev`
And in R:  `install.package(c('sf','rgdal'))`
This worked.  Could this be a problem with not installing dependencies `--no-install-recommends`?

This was not just a problem for me.  But for others also running this script on EC2 ubuntu machine.

**Comment by Jtsmith275** [comment]
Thanks for this I am having another look into why this happening
